### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by dawuwu** [nolimits4web/Framework7-Vue#3]
When I run 'npm run dev' I get the following error:

C:\f7vue\node_modules\cross-env\dist\index.js:58
  var envVars = Object.assign({}, process.env);
                       ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at getCommandArgsAndEnvVars (C:\f7vue\node_modules\cross-env\dist\index.js:58:24)
    at crossEnv (C:\f7vue\node_modules\cross-env\dist\index.js:22:35)
    at Object.<anonymous> (C:\f7vue\node_modules\cross-env\bin\cross-env.js:3:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

npm ERR! framework7-vue@0.5.0 dev: `cross-env NODE_ENV=development webpack-dev-server --content-base kitchen-sink/ --open --inline --hot`
npm ERR! Exit status 8

**Comment by nolimits4web** [comment]
What is your node and npm versions? Try upgrading node to 6.x+

**Comment by dawuwu** [comment]
thanks, that fixed the error
